### ISSUE TITLE
Freeze When Display DPI/Resolution changed

### ISSUE THREAD

**Issue by Pein1911** [openhardwaremonitor/openhardwaremonitor#1252]
My display is 1440p, sometime if i load a game at 1080p fullscreen, then I quit game and  OHM tray icon will be freeze

**Comment by wingo1** [comment]
Same problem !

**Comment by pkypkygit** [comment]
The same problem here. 

The easiest way to reproduce:
1. set windows DPI scaling to 100%
2. start OpenHWMonitor, minimize it 
3. set windows DPI scaling to 125%
4. OpenHWMonitor is frozen, stops redrawing values in systray

**Comment by moellerm** [comment]
This should be fixed in version 0.9.3.

**Comment by pkypkygit** [comment]
Hello.

I have tried it in version 0.9.3 and the problem is still there. Windows TaskManager says that Open Hardware Monitor is "not responding".

Regards.

**Comment by pkypkygit** [comment]
Thanks!

Confirmed - I have tried the new version and it works.

Regards.

> 
> 
> This should be fixed in version 0.9.4.
